Improve import of NumpyHistogram.
Import of numpy in NumpyHistogram.__init__  is more robust than in module's __init__.py.
For example, today when testing Lena I got a very strange error during import of numpy,
which was connected to subprocess (which works fine in other places and from Python 2):

$ python -c 'import numpy'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/numpy/__init__.py", line 145, in <module>
    from . import core
  File "/usr/lib/python3.9/site-packages/numpy/core/__init__.py", line 102, in <module>
    from . import _internal
  File "/usr/lib/python3.9/site-packages/numpy/core/_internal.py", line 10, in <module>
    import platform
  File "/usr/lib/python3.9/platform.py", line 119, in <module>
    import subprocess
  File "/usr/lib/python3.9/subprocess.py", line 227, in <module>
    _PopenSelector = selectors.SelectSelector
AttributeError: module 'selectors' has no attribute 'SelectSelector'